## Intro to NumPy
NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays (https://en.wikipedia.org/wiki/NumPy).

Numpy is incredibly fast, as it has bindings to C libraries.

In [25]:
import numpy as np

## Creation of NumPy array
### From a list

In [26]:
a_list = [1, 2, 3]
a_array = np.array(a_list)

In [27]:
print(type(a_list))
print(type(a_array))

<class 'list'>
<class 'numpy.ndarray'>


In [28]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
a_2D = np.array(matrix)

### Using built-in methods

In [29]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(0, 10, 2) # np.arange(start, stop, step)

array([0, 2, 4, 6, 8])

In [31]:
np.zeros(3)

array([0., 0., 0.])

In [32]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.linspace(0, 10, 20) # np.linspace(start, stop, num=50)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## Random

### uniform
Return an array of the given shape with random samples from a uniform distribution

In [34]:
np.random.uniform(0, 1, 5) # (low, high, size)

array([0.891773  , 0.96366276, 0.38344152, 0.79172504, 0.52889492])

### randn
Return samples from the “standard normal” distribution.

In [35]:
np.random.randn(2,2) # standard normal (Gaussian) distribution of mean 0 and variance 1

array([[0.76103773, 0.12167502],
       [0.44386323, 0.33367433]])

### normal

In [36]:
mu, sigma = 1, 0.5 # mean and standard deviation
np.random.normal(mu, sigma, size = (3, 2))

array([[ 1.74703954,  0.89742087],
       [ 1.15653385,  0.57295213],
       [-0.27649491,  1.3268093 ]])

### multivariate normal

In [37]:
mean = [1, 2]
cov = [[1, 0], [0, 1]]
np.random.multivariate_normal(mean, cov, size= (3, 2))

array([[[1.8644362 , 1.25783498],
        [3.26975462, 0.54563433]],

       [[1.04575852, 1.81281615],
        [2.53277921, 3.46935877]],

       [[1.15494743, 2.37816252],
        [0.11221425, 0.01920353]]])

### randint
Return random integers

In [38]:
np.random.randint(1, 100, 5) # randint(low, high=None, size=None)

array([66, 42, 58, 36, 12])

### seed()
The seed() method is used to initialize the random number generator.

In [39]:
np.random.seed(0)

### Operations

In [40]:
arr = np.arange(0, 10)
arr_r = arr.reshape(2, 5)
print('arr: ')
print(arr)
print('arr_r: ')
print(arr_r)

arr: 
[0 1 2 3 4 5 6 7 8 9]
arr_r: 
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [41]:
my_arr = np.random.randint(1, 100, 10)
print(my_arr)

[45 48 65 68 68 10 84 22 37 88]


In [42]:
my_arr.max()

np.int64(88)

In [43]:
my_arr.argmax()

np.int64(9)

In [44]:
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])

In [45]:
arr_1 + arr_2

array([5, 7, 9])

In [46]:
arr_1 * arr_2

array([ 4, 10, 18])

In [47]:
np.exp(arr_1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [48]:
np.log(arr_1)

array([0.        , 0.69314718, 1.09861229])